### ISSUE TITLE
storage download and list files not returning responses

### ISSUE THREAD

**Issue by j-lim-sigma** [JohnCoene/firebase#26] opened 2022-03-09 07:19 UTC
Hi, I tried the demo sample code in the documentation, however, no responses are returned for both methods. Am I missing something? Thank you.

**Comment by JohnCoene** [comment] 2022-03-09 18:30
Do you have everything configured correctly in your Google console? Also make sure you have the environment variables set properly, see [config](https://firebase.john-coene.com/guide/config/)

**Comment by j-lim-sigma** [comment] 2022-03-09 21:46
Yes. Auth, upload and delete works just fine (files are uploaded and deleted). Not sure about download. I did not change any of the sample code, this here returns null: 

observeEvent(s$get_response("dl"), {
    print(s$get_response("dl"))
  })

**Comment by JohnCoene** [comment] 2022-03-13 08:51
I pushed a fix, can you install from Github and try again with the code below?
I think `get_response` breaks on later shiny versions

```r
library(shiny)
library(firebase)

ui <- fluidPage(
  useFirebase(), # import dependencies
  firebaseUIContainer(),
  reqSignin(h4("Logged in!")), # hide from UI
  uiOutput("uploadUI"),
  uiOutput("downloadUI"),
  uiOutput("deleteUI")
)

server <- function(input, output){
  f <- FirebaseUI$
    new()$ # instantiate
    set_providers( # define providers
      email = TRUE, 
      google = TRUE
    )$
    launch() # launch

  s <- Storage$new()$
    ref("logo.png")
  
  # upload a file
  output$uploadUI <- renderUI({
    f$req_sign_in()

    actionButton("upload", "Upload Image")
  })

  observeEvent(input$upload, {
    s$upload_file("docs/logo.png", "up")
  })

  observeEvent(input$up, {
    print(input$up)
  })
  
  # download a file
  output$downloadUI <- renderUI({
    f$req_sign_in()

    actionButton("download", "Download Image")
  })

  observeEvent(input$download, {
    s$download_file("dl")
  })

  observeEvent(input$dl, {
    print(input$dl)
  })
  
  # delete file
  output$deleteUI <- renderUI({
    f$req_sign_in()

    actionButton("delete", "Delete Image")
  })

  observeEvent(input$delete, {
    s$delete_file("del")
  })

  observeEvent(input$del, {
    print(input$del)
  })
}

shinyApp(ui, server)
```

**Comment by j-lim-sigma** [comment] 2022-03-14 03:24
Thanks. Tested again. input$del works, returning the responses. get_response() method still returning null. I suppose this solves the problem.

**Comment by JohnCoene** [comment] 2022-03-14 05:48
This is very strange.
Can you copy paste the code you use here to make sure we are running the same?

**Comment by j-lim-sigma** [comment] 2022-03-14 06:35
This is the code I run: 

```R
library(shiny)
library(firebase)

ui <- fluidPage(
  useFirebase(), # import dependencies
  firebaseUIContainer(),
  reqSignin(h4("Logged in!")), # hide from UI
  uiOutput("uploadUI"),
  uiOutput("downloadUI"),
  uiOutput("deleteUI")
)

server <- function(input, output){
  f <- FirebaseUI$
    new()$ # instantiate
    set_providers( # define providers
      email = TRUE, 
      google = TRUE
    )$
    launch() # launch
  
  s <- Storage$new()$
    ref("test.png")
  
  # upload a file
  output$uploadUI <- renderUI({
    f$req_sign_in()
    
    actionButton("upload", "Upload Image")
  })
  
  observeEvent(input$upload, {
    s$upload_file("docs/logo.png", "up")
  })
  
  observeEvent(input$up, {
    print(input$up)
  })
  
  # download a file
  output$downloadUI <- renderUI({
    f$req_sign_in()
    
    actionButton("download", "Download Image")
  })
  
  observeEvent(input$download, {
    s$download_file("dl")
  })
  
  observeEvent(input$dl, {
    print(input$dl)
  })
  
  # delete file
  output$deleteUI <- renderUI({
    f$req_sign_in()
    
    actionButton("delete", "Delete Image")
  })
  
  observeEvent(input$delete, {
    s$delete_file("del")
  })
  
  observeEvent(input$del, {
    print(input$del)
  })
}

shinyApp(ui, server)
```

From the above, input$dl and input$del return responses. 

I also run another script, calling get_response() method:

```R
library(shiny)
library(firebase)

ui <- fluidPage(
  useFirebase(), # import dependencies
  firebaseUIContainer(),
  reqSignin(h4("Logged in!")), # hide from UI
  uiOutput("uploadUI"),
  uiOutput("downloadUI"),
  uiOutput("deleteUI")
)

server <- function(input, output, session){
  f <- FirebaseUI$
    new(persistence = "local")$ # instantiate
    set_providers( # define providers
      email = TRUE, 
      google = TRUE
    )$
    launch() # launch
  
  s <- Storage$new()$
    ref("test.png")
  
  # upload a file
  output$uploadUI <- renderUI({
    f$req_sign_in()
    
    actionButton("upload", "Upload Image")
  })
  
  observeEvent(input$upload, {
    s$upload_file("DESC.txt", response = "upload")
  })
  
  observeEvent(s$get_response("upload"), {
    print("observe", s$get_response("upload"))
  }, ignoreNULL = FALSE)
  
  # download a file
  output$downloadUI <- renderUI({
    f$req_sign_in()
    
    actionButton("download", "Download Image")
  })
  
  observeEvent(input$download, {
    s$download_file("dl")$get_response("dl")
    print("download", s$get_response("dl"))
    x <<- s$get_response("dl")
  })
  
  observeEvent(s$get_response("dl"), {
    print(s$get_response("dl"))
    x2 <<- s$get_response("dl")
  })
  
  # delete file
  output$deleteUI <- renderUI({
    f$req_sign_in()
    
    actionButton("delete", "Delete Image")
  })
  
  observeEvent(input$dl, {
    print(input$dl)
    x <<- input$dl
  })
  
  
  observeEvent(input$delete, {
    s$delete_file("del")
  })
  
  observeEvent(input$del, {
    print(input$del)
    y <<- input$del
  })
  
  observeEvent(s$get_response("del"), {
    print(s$get_response("del"))
    y2 <<- s$get_response("del") #keeping the response after session terminated. 
  })
  
}

shinyApp(ui, server)
```

The 2nd script, input$del and input$dl return the same responses as first script (as expected), but get_response() returns null.

**Comment by JohnCoene** [comment] 2022-03-30 10:09
I'm sorry, I can't reproduce this.
Could you check the environment variables and make sure all is well there?
Also reinstall from Github to make sure you have the latest functioning version.

**Closed** 2024-05-20 21:22 UTC
